spring:
  datasource:
    url: jdbc:mysql://localhost:3306/douyin
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#  security:
#    user:
#      password: 123456
#      name: root
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
   mapper-locations: classpath:/mapper/*.xml
server:
  port: 8081